cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/cask'

# Install ZSH
brew 'zsh'
brew 'zsh-completions'

# Install Python
brew 'python'
brew 'python3'
brew 'pyenv'

brew 'ack'
# brew 'ansible'
# brew 'ansible-lint'
# brew 'ask-cli'
brew 'awscli'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'grc'
brew 'hub'
brew 'jq'
brew 'mackup'
brew 'mas'
brew 'mongodb'
brew 'netcat'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'tree'
brew 'unrar'
brew 'wget'

cask 'alfred'
cask 'cheatsheet'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'hyper'
cask 'iterm2'
cask 'pgadmin4'
cask 'postman'
cask 'slack'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'font-hack-nerd-font'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'

cask 'steam'
