#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done


# Set default shell.
echo "$(which zsh)" >> /etc/shells
chsh -s $(which zsh)

# Configure Hyper.
ln -sf ~/.dotfiles/hyper/hyper.js ~/.hyper.js
ln -sf ~/.dotfiles/hyper/hyper.css ~/.hyper.css